### ISSUE TITLE
ranger keeps looking for finder window after follow exit

### ISSUE THREAD

**Issue by NationAdel** [Bellavene/findger#1]
Hi,
Great addition to ranger. using the powerful image rendering of macOS is pleasing.
when I toggle follow everything works fine but after exit I get an error in the middle of ranger
: Can't set Finder window 1 to POSIX file "file\path". (-10006).

**Comment by Bellavene** [comment]
Hello,
Strange, I don't have such message. There is a command that will not display any message in ranger after execution of a command. Don't remember it right now, you can find it on ranger's wiki or maybe I will check it later at free time.

**Comment by NationAdel** [comment]
what is the best way to map the jk to follow i used these two line to change the mappings.
            self.fm.execute_console("map k          chain move up=1;    follow_files_in_finder")
            self.fm.execute_console("map j          chain move down=1;  follow_files_in_finder")

in the commands.py.
or is there a way to map in rc.conf

**Comment by Bellavene** [comment]
add it to commands.py
and add without follow_files_in_finder in next section in else. So it will revert back if not following.

**Comment by Bellavene** [comment]
Any progress? Is your weird message gone?
As you have asked about mappings, sadly now it is done in commands.py
Would be glad if someone makes a contribution and makes it better, I am not a coder.

**Comment by Bellavene** [comment]
Rewrote the code. There is no need anymore to edit the code for correct keymapings.
